services:
  async-test:
    build: .
    ports:
      - "8181:8080"
      - "9986:9986"
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9986
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge